version: '3'
services:
  dwapi:
#    image: wyveo/nginx-php-fpm:latest
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: dwapi
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=dwapidb"
    volumes:
      - ./:/var/www
#      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    ports:
      - 8080:80

  dwapidb:
    image: mysql:5.6
    container_name: dwapidb
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports:
      - "33061:3306"

volumes:
  dbdata:
